### PR TITLE
adding Irish whistle (partial)

### PR DESCRIPTION
**Pull request by cal-invisible**

### CODE REVIEW

**Comment by cal-invisible** [comment]
linked to this issue: https://github.com/amunn/recorder-fingering/issues/1

**Comment by amunn** [comment]
Thanks for the suggestion to add tin whistle support. I've implemented things differently from this pull request, and so am not incorporating your code into the package.

**Comment by cal-invisible** [comment]
great, I just updated my fork with your source and checked that all is ok. I just had to map `\Irish->\Whistle` and to add `\fingeringSetup{width=12pt}`.
Thank you!

**Comment by amunn** [comment]
Yes, because the whistle has no thumb hole, it requires a smaller width to display at a good size.

**Pull request closed without merging**
